stages:
  - build

.build: &build
  stage: build
  script:
    - opam list | grep coq
    - make Makefile.coq
    - make -j$(nproc) -f Makefile.coq pretty-timed
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - "**/*.glob"
      - "**/*.vo*"
      - "**/.*.aux"
      - ".*.cache"
      - "_build"

"8.16.1-iris40":   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.16.1_iris-4.0.0_equations-1.3"}
"8.17.1-iris40":   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.17.1_iris-4.0.0_equations-1.3"}
"8.17.1-iris41":   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.17.1_iris-4.1.0_equations-1.3"}
"8.18.0-iris41":   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.18.0_iris-4.1.0_equations-1.3"}
