stages:
  - build

.build: &build
  stage: build
  script:
    - opam list | grep coq
    - make Makefile.coq
    - make -j$(nproc) -f Makefile.coq pretty-timed
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - "**/*.glob"
      - "**/*.vo*"
      - "**/.*.aux"
      - ".*.cache"
      - "_build"

"8.15.2":   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.15.2"}
"8.16.1":   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.16.1"}
#dev:   {<<: *build, image: "ghcr.io/katamaran-project/coq:dev"}
